CREATE TABLE IF NOT EXISTS users (
	 `id` BIGINT AUTO_INCREMENT,
	,`username` VARCHAR(64) NOT NULL
	,`password` BLOB NOT NULL,
	,`created_by` BIGINT DEFAULT 1
	,`created_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,`updated_by` BIGINT DEFAULT 1
	,`updated_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (id)
);